services:
  # --- Public entrypoint (Nginx) ---
  - type: web
    name: nginx
    env: docker
    rootDir: ./nginx
    dockerfilePath: ./nginx/Dockerfile
    plan: free
    envVars:
      - key: UPSTREAM1
        value: app1:8080
      - key: UPSTREAM2
        value: app2:8080
      - key: UPSTREAM3
        value: app3:8080
    # Nginx must listen on $PORT inside the container (handled in your templated conf)

  # --- Private backend replicas ---
  - type: pserv 
    name: app1
    env: docker
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    

  - type: pserv
    name: app2
    env: docker
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    

  - type: pserv
    name: app3
    env: docker
    rootDir: ./backend
    dockerfilePath: ./backend/Dockerfile
    

  # --- Private Postgres with persistent Disk ---
  - type: pserv
    name: db
    env: docker
    image:
      url: postgres:16-alpine   # <-- object with url (not a bare string)    
    disk:
      name: pgdata
      mountPath: /var/lib/postgresql/data
      sizeGB: 10
