services:
  # --- Public entrypoint (Nginx) ---
  - type: web
    name: nginx
    runtime: docker
    rootDir: ./nginx
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: UPSTREAM1
        value: http://app1:8080
      - key: UPSTREAM2
        value: http://app2:8080
      - key: UPSTREAM3
        value: http://app3:8080

  # --- Private backend replicas ---
  - type: pserv 
    name: app1
    runtime: docker
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    plan: free

  - type: pserv
    name: app2
    runtime: docker
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    plan: free

  - type: pserv
    name: app3
    runtime: docker
    rootDir: ./backend
    dockerfilePath: ./Dockerfile
    plan: free

  # --- Private Postgres with persistent Disk ---
  - type: pserv
    name: db
    runtime: image
    image:
      url: docker.io/postgres:16-alpine
    plan: free
    envVars:
      - key: POSTGRES_PASSWORD
        value: abcd1234
      - key: POSTGRES_USER
        value: myuser
      - key: POSTGRES_DB
        value: mydb
    disk:
      name: pgdata
      mountPath: /var/lib/postgresql/data
      sizeGB: 1